dataset:
  repo_id: rebot_sim/rebot_act_red_cylinder
  root: ./data_act_sim/rebot_act_red_cylinder
  task: put_red_cylinder_on_plate
  fps: 50

environment:
  xml: ./rebot_act_sim/assets/example_scene_rebot_red_cylinder.xml
  seed: 0
  success_hold_seconds: 0.5
  camera_render_hz: 25
  object_randomization:
    plate_position: [0.27, -0.16, 0.82]
    target_object_position_center: [0.32, 0.08, 0.8205]
    target_object_xy_half_range: [0.025, 0.025]
  teleop:
    motion_alpha: 0.25
  tactile_processing:
    signal_source: distance_proximity
    normal_axis: 2
    projection_sigma: 0.0025
    clip_max: 1.0
    temporal_ema_alpha: 0.25
    spatial_smoothing: true
    contact_time_constant: 0.01
    proximity_sigma: 0.00030
    proximity_reach: 0.00125
    proximity_threshold: 0.05
    visualization_color_max: 1.0

policy:
  type: act
  chunk_size: 50
  n_action_steps: 25
  vision_backbone: resnet18
  pretrained_backbone_weights: ResNet18_Weights.IMAGENET1K_V1
  use_vae: true
  latent_dim: 32
  kl_weight: 10.0
  temporal_ensemble_coeff: null
  device: cuda

multimodal:
  use_imu: false
  use_tactile: false
  sensor_embed_dim: 64

training:
  output_dir: ./rebot_act_sim/ckpt/act_sim_red_cylinder
  steps: 8000
  batch_size: 4
  num_workers: 8
  learning_rate: 0.0001
  weight_decay: 0.0001
  seed: 42
  log_freq: 50
  save_freq: 2000
